### ISSUE TITLE
[QUESTION] Need update the version to reflect on another repo?

### ISSUE THREAD

**Issue by felipeneri** [Luehang/react-native-page-list#7]
Hi Lue, 
I use your "react-native-gallery-swiper" lib and it has a dependency of lib "react-native-page-list". I have opened a pull request to "react-native-page-list" and was merged, but not yet updated on NPM.

I would like to know if NPM updates automatically or if it is necessary to change lib version to reflect dependencies updates.

Thank's.

**Comment by Luehang** [comment]
Hi,

Thanks for contributing.

Some of it is done manually.  I just publish the package.  If you currently have `react-native-gallery-swiper` or `react-native-page-list` installed, update `react-native-page-list` to latest. 

```bash
$ npm install react-native-page-list@latest
```
